config/routes.rb
Medium::Application.routes.draw do
  resources :user, only: [:show, :edit, :update]
  resources :post, only: [:show, :edit, :update]
  root 'genrepages#home'
  get  '/signup',      to: 'user#new'
  get  '/login',       to: 'sessions#new'
  get  '/newpost',     to: 'post#new'

  post 'sessions/create', to: 'sessions#create'
  post 'user/create',     to: 'user#create'
  post 'post/create',     to: 'post#create'

end

app/models/genre.rb
# == Schema Information
#
# Table name: genres
#
#  id         :integer          not null, primary key
#  genre_name :text
#  created_at :datetime
#  updated_at :datetime
#

class Genre < ActiveRecord::Base
  validates_presence_of :id, :genre_name
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  header     :text
#  content    :text
#  genre_id   :integer
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  validates_presence_of :content, :header
  validates :content, uniqueness: true, length: {minimum: 30}
  validates :header, uniqueness: true, length: {minimum: 10}
  before_save 

  #private 
  #  newline = "/n/r"
  #  def HTMLify(content)
  #    if /#{newline}/.match(content)
  #  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id            :integer          not null, primary key
#  email         :string(255)
#  name          :string(255)
#  auth_token    :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#  password_hash :text
#  password_salt :text
#  description   :text
#

class User < ActiveRecord::Base
  has_many :posts
  validates_presence_of :password, :password_confirmation, :on => :create
  attr_accessor :password, :password_confirmation
  before_save :encrypt_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #validate :password, length: {minimum: 6}
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX },
                    uniqueness: {case_sensitive: false}
  validates :description, length: {minimum: 10}

  before_create {generate_token(:auth_token)}

  def self.authenticate(options={})
    user = find_by email: options[:email]
    if user && user.password_hash == BCrypt::Engine.hash_secret(options[:password], user.password_salt)
      user
    else
      nil
    end
  end

  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  add_flash_types :notice, :error, :success, :alert
  protect_from_forgery with: :exception
  
end

app/controllers/genrepages_controller.rb
class GenrepagesController < ApplicationController
  include SessionsHelper
  include PgHelper
  def home
    @posts = find_all_posts
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  include SessionsHelper
  before_filter :signed_in_user, :only => [:new, :create, :edit]

  def new
    @post = Post.new
    @url = '/post/create'
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to user_path(current_user.id), success: 'Post creation successful!'
    else
      redirect_to newpost_path, error: 'Post failed!'
    end
  end

  def show
    @post = Post.find_by id: params[:id]
    @user = User.find_by id: @post.user_id
  end

  def edit
    @post = Post.find_by id: params[:id]
    @url = '/post/' + params[:id]
  end

  def update
    @post = Post.find_by id: params[:id]
    if @post.update_attributes(post_params)
      redirect_to @post, success: 'Editing successful!'
    else
      redirect_to edit_post_path(@post.id), error: 'Editing failed!'
    end
  end

  private 
    def post_params
      params.require(:post).permit!
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  def new
    @user = User.new
  end

  def create
    @user = User.authenticate(user_params)
    if @user
      sign_in @user
      redirect_to @user, success: 'Successful login!'
    else
      redirect_to login_path, error: 'Sorry, wrong credentials!'
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  include SessionsHelper
  include PgHelper
  before_filter :signed_in_user, :only => [:show, :edit, :update]
  before_filter :correct_user, :only => [:show, :edit]

  def new
    @user = User.new
    @url = 'user/create'
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: "Creation successful!"
    else
      redirect_to user_new_path, error: "Login fail"
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = find_posts_by_user_id @user.id
    @editing = true if signed_in?
  end

  def edit
    @user = User.find(params[:id])
    @url = '/user/' + params[:id]
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user, success: 'Editing successful!'
    else
      redirect_to edit_user_path(@user.id), error: 'Editing failed!'
    end
  end

  private
    def user_params
      params.require(:user).permit!
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then 'notice_msg'
    when :success then 'success_msg'
    when :error then 'error_msg'
    when :alert then 'alert_msg'
    end
  end
end

app/helpers/genrepages_helper.rb
module GenrepagesHelper
end

app/helpers/pg_helper.rb
module PgHelper
  def find_posts_by_user_id(id)
    sqlquery = 'SELECT * FROM posts WHERE user_id = ' + id.to_s + 'ORDER BY created_at DESC'
    return Post.find_by_sql(sqlquery)
  end

  def find_all_posts
    sqlquery = 'SELECT * FROM posts ORDER BY created_at DESC'
    return Post.find_by_sql(sqlquery)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies[:auth_token] = user.auth_token
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by auth_token: cookies[:auth_token]
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user = nil
    cookie.delete[:auth_token]
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to login_path, error: "Log in please"
    end
  end

  def correct_user
    unless current_user?(User.find_by id: params[:id])
      store_location
      redirect_to login_path, error: "Wrong user"
    end
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/genrepages/_landing.html.erb
<h1>Medium platform</h1>
<p>
  A place to read and write things for fun!
  <br><br>
  Read stuff, yay!
</p>
<div class="option-body">
  <% if signed_in? %>
  <a class="btn" href='<%= user_path(current_user) %>'>Profile</a>
  <% else %>
  <a class="btn" href='<%= login_url %>'>Sign in!</a>
  <% end %>
</div>

app/views/genrepages/home.html.erb
<%= render partial: 'layouts/flash_messages' %>
<%= render partial: 'layouts/main_ui', locals: {content: 'landing', posts: 'shared/indv_post', outerBackground: 'sky-blue-background', innerBackground: 'dark-gradient'} %>

app/views/layouts/_flash_messages.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="flash <%= flash_class(key) %> fade in">
      <%= value %>
      <a class="hide_flash">x</a>
    </div>
  <% end %>
</div>

app/views/layouts/_main_ui.html.erb
<div class="main-container">
  <% if defined?(outerBackground) %>
  <aside class="cover <%= outerBackground %>">
  <% else %>
  <aside class="cover">
  <% end%>
    <% if defined?(innerBackground) %>
    <div class="cover-body <%= innerBackground %>">
    <% else %>
    <div class="cover-body">
    <% end %>
      <div class="cover-body-inner">
        <%= render partial: content %>
      </div>
    </div>
  </aside>
  <div class="content-container">
    <div class="inner-content-container">
      <% if defined?(posts) %>
        <%= render partial: posts %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Medium</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=PT+Serif' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/post/_create_post.html.erb
<script type="text/javascript" src="http://js.nicedit.com/nicEdit-latest.js"></script>
<script type="text/javascript">
//<![CDATA[
        bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
//]]>
</script> 
<div class="new-post-container">
  <div class="create-post-form">
    <h1>Create Post</h1>
    <%= form_for(@post, :url => @url) do |p| %>
      <%= p.text_field :header, :class => 'user-input', :placeholder => 'Header', :cols => '40' %>
      <br>
      <br>
      <%= p.text_area :content, :class => 'redact-config', :placeholder => 'Content' %>
      <br>
      <br>
      <%= p.submit(:class => 'btn-submit btn') %>
    <% end %>
  </div>
</div>

app/views/post/edit.html.erb
<%= render partial: 'layouts/flash_messages' %>
<%= render partial: 'create_post' %>

app/views/post/new.html.erb
<%= render partial: 'layouts/flash_messages' %>
<script type="text/javascript" src="http://js.nicedit.com/nicEdit-latest.js"></script>
<script type="text/javascript">
//<![CDATA[
        bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
//]]>
</script> 
<div class="new-post-container">
  <div class="create-post-form">
    <h1>Create Post</h1>
    <%= form_for(@post, :url => post_create_path) do |p| %>
      <%= p.text_field :header, :class => 'user-input', :placeholder => 'Header', :cols => '40' %>
      <br>
      <br>
      <%= p.text_area :content, :class => 'redact-config', :placeholder => 'Content' %>
      <br>
      <br>
      <%= p.submit(:class => 'btn-submit btn') %>
    <% end %>
  </div>
</div>

app/views/post/show.html.erb
<%= render partial: 'layouts/flash_messages' %>
<div class="post-wrapper-outer">
  <div class="post-wrapper-inner">
    <div class="post-aside-wrapper">
      <div class="post-aside">
        <p><%= @user.name %></p>
        <p><%= @user.description %></p>
      </div>
      <div class="post-header">
        <h1><%= @post.header %></h1>
      </div>
      <div class="post-content">
        <p><%= simple_format(@post.content.html_safe) %></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_indv_post.html.erb
<% @posts.each do |n| %>
  <h1><a class="header_link" href="/post/<%= n.id %>"><%= n.header %></a></h1>
  <% if defined?(@editing) && @editing %>
    <li class="edit-link"><a href=<%= edit_post_path(n.id) %>>edit</a></li>
  <% end %>
  <hr>
  <p><%= simple_format(n.content.truncate(400).html_safe) %></p>
<% end %>

app/views/user/_profile.html.erb
<div class="profile_container">
  <h1><%= @user.name %></h1>
  <hr>
  <p><%= @user.description %></p>
  <a href="<%= edit_user_path(@user.id) %>" class='btn btn-submit'>Edit Profile</a>
  <a href="<%= newpost_path %>" class='btn btn-submit'>Create Post</a>
</div>

app/views/user/_user_form.html.erb
<%= form_for(@user, :url => @url) do |u| %>
  <%= u.text_field(:name, { class: 'user-input', :placeholder => 'Name' })%>
  <%= u.text_field(:email, { class: 'user-input',  :placeholder => 'Email Address' }) %>
  <%= u.text_area(:description, { class: 'user-input', :placeholder => 'Describe yourself'})%>
  <% if defined?(password) && password %>
    <%= u.password_field(:password, { class: 'user-input',  :placeholder => 'Password' }) %>
    <%= u.password_field(:password_confirmation, {class: 'user-input', :placeholder => 'Confirm Password'})%>
  <% end %>
  <%= u.submit(class: 'btn btn-submit') %>
<% end %>

app/views/user/edit.html.erb
<%= render partial: 'layouts/flash_messages' %>
<div class="edit-profile-container">
  <h1>Edit User</h1>
  <%= render partial: 'user_form', locals: {password: false} %>
</div>

app/views/user/new.html.erb
<div class="form-container">
  <div class="form-header">
    <h1>Create User</h1>
  </div>
  <div class="create-form">
    <h1>Hi there!<h1>
    <%= render partial: 'user_form', locals: {password: true} %>
  </div>
</div>

app/views/user/show.html.erb
<%= render partial: 'layouts/flash_messages' %>
<%= render partial: 'layouts/main_ui',
    locals: {user: @user, 
          posts: 'shared/indv_post', 
          content: 'profile', 
          outerBackground: 'profile-outer-background', 
          innerBackground: 'profile-inner-background', 
    } 
%>